# Page settings
baseURL = "https://zeng-yirong.github.io/"
languageCode = "en"
title = "Hi, I'm Yirong"
theme = "hugo-devresume-theme"
publishDir = "docs"

[params]
    author = "Yirong Zeng"
    description = "Yirong Zeng's Academic Resume"

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Yirong Zeng (曾屹荣)"
        tagline = "PhD Student"
        avatar = "me.png"

    [params.contact]
        enable = true
        location = "Harbin"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:yrzeng@ir.hit.edu.cn"
        text = "Mail"
        [[params.contact.list]]
        icon = "fab fa-google"
        url = "https://scholar.google.com/citations?user=HZgQfW0AAAAJ"
        text = "Google Scholar"

    [params.skills]
        enable = false

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "PhD - Computer Science"
        university = "Harbin Institute of Technology"
        dates = "2022 - Present"
        [[params.education.list]]
        degree = "Bachelor - Computer Science"
        university = "Harbin Engineering University"
        dates = "2018 - 2022"

    [params.awards]
        enable = false

    [params.internships]
        enable = true

        [[params.internships.list]]
        name = "2024.9-present Huawei (华为小艺 北京)"
        [[params.internships.list]]
        name = "2023.7-2023.12 China Academy of Cyber (中国网络空间安全研究院，北京)"
        [[params.internships.list]]
        name = "2021.12-2022.5 NEC (日电中国，北京)"

    [params.hobbies]
        enable = true

        [[params.hobbies.list]]
        name = "Skiing/Badminton"

    [params.languages]
        enable = false

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Tool Learning"
        [[params.interests.list]]
        name = "Agentic RL"
        [[params.interests.list]]
        name = "Misinformation Detection"

    [params.summary]
        enable = true
        text = "I'm a 4th Ph.D. student in Research Center for Social Computing and Information Retrieval (SCIR), at Harbin Institute of Technology (HIT, China). I am advised by Prof. Liu Ting. I obtained my bachelor degree in June 2022. My research interests include Tool Learning, Agentic RL, misinformation detection."

    [params.experience]
        enable = false

    [params.projects]
        enable = false

    [params.information]
        enable = true

        [[params.information.list]]
        title = "AutoTool: Automatic Scaling of Tool-Use Capabilities in RL via Decoupled Entropy Constraints."
        name = "Yirong Zeng, Xiao Ding, Yufei Liu, Yuxian Wang, Qunyao Du, Yutai Hou, Wu Ning, Haonan Song, Duyu Tang, Dandan Tu, et al."
        publisher = "ICLR 2026"
        href = "https://iclr.cc/virtual/2026/poster/10006467"
        details = ""

        [[params.information.list]]
        title = "Precision over Diversity: High-Precision Reward Generalizes to Robust Instruction Following."
        name = "Yirong Zeng, Yufei Liu, Xiao Ding, Yutai Hou, Yuxian Wang, Haonan Song, Wu Ning, Dandan Tu, Qixun Zhang, Bibo Cai, et al."
        publisher = "arXiv 2026"
        href = "https://arxiv.org/abs/2601.04954"
        details = ""

        [[params.information.list]]
        title = "iTool: Reinforced Fine-Tuning with Dynamic Deficiency Calibration for Advanced Tool Use."
        name = "Yirong Zeng, Xiao Ding, Yuxian Wang, Weiwen Liu, Wu Ning, Xu Huang, Duyu Tang, Dandan Tu, Bing Qin, Ting Liu"
        publisher = "EMNLP 2025 | Main"
        href = "https://aclanthology.org/2025.emnlp-main.701.pdf"
        details = ""

        [[params.information.list]]
        title = "Tool Zero: Training Tool-Augmented LLMs via Pure RL from Scratch."
        name = "Yirong Zeng, Xiao Ding, Yutai Hou, Yuxian Wang, Li Du, Juyi Dai, Qiuyang Ding, Duyu Tang, Dandan Tu, Weiwen Liu, Bing Qin, Ting Liu"
        publisher = "EMNLP 2025 | Finding"
        href = "https://aclanthology.org/2025.findings-emnlp.485.pdf"
        details = ""

        [[params.information.list]]
        title = "Human Cognitive Process Aligned Rumor Detection with Small Language Models Enhanced Large Language Models."
        name = "Yirong Zeng, Xiao Ding, Bibo Cai, Bing Qin, Ting Liu"
        publisher = "Information Processing & Management 2026"
        href = "https://www.sciencedirect.com/science/article/abs/pii/S0306457326000518"
        details = ""

        [[params.information.list]]
        title = "Moderation Matters: Exploring Large Language Models for Effective Rumor Detection on Social Media."
        name = "Yirong Zeng, Xiao Ding, Bibo Cai, Ting Liu and Bing Qin"
        publisher = "NAACL 2025 | Main"
        href = "https://aclanthology.org/2025.naacl-long.128.pdf"
        details = ""

        [[params.information.list]]
        title = "RU22Fact: Optimizing Evidence for Multilingual Explainable Fact-Checking on Russia-Ukraine Conflict."
        name = "Yirong Zeng, Xiao Ding, Yi Zhao, Xiangyu Li, Jie Zhang, Chao Yao, Ting Liu and Bing Qin"
        publisher = "Coling 2024"
        href = "https://aclanthology.org/2024.lrec-main.1239/"
        details = ""

    [params.software]
        enable = true

        [[params.software.list]]
        title = "Misinformation Detection"
        name = "Yirong Zeng, Juyi Dai, Shen You"
        meta = "Demo System"
        href = "https://huggingface.co/spaces/You-shen/React"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/zeng-yirong"
        title = "zeng-yirong"
